# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NDkyYzMzYjFjN2VkN2FiYWJkMjA3ZmM2MDRiYmQyMWE3NmZhNjY0M2FlMzBlYTY5Zjg2OGY3YjY0NjYxOTNmZjRiYjQ2ZWY5MzI0ZGMyMDVmOTM2ZDNkYjYxYjcyMDE2MDlhM2ZlNmU0OGZlNGZjNDJlN2MwZGQxOGIyNTJlYTc=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
